### ISSUE TITLE
Config file?

### ISSUE THREAD

**Issue by t-e-s-tweb** [rnetx/cdns#1]
Is there any configuration example? 

Also is it going to be different or its a fork of mosdns? Some of the code points towards that.

**Comment by 0xffffharry** [comment]
This is a new dns server, the basic functionality has been completed. And the sample configuration file has not been created yet.

You can write down your requirements here and I will write sample configuration files based on those requirements here.

**Comment by t-e-s-tweb** [comment]
Okay. Currently I am using blocky https://github.com/0xERR0R/blocky

The features are blocklists, whitelists, ability to serve over DNS over http and HTTPS server, TLS HTTPS and plain for upstream. I am using this because out of everything else the memory usage of this is very very  small. 

Basic requirements are as above. Encryption for upstream, DNS over http for server, blacklists whitelists and small memory usage.

**Comment by 0xffffharry** [comment]
<details>
<summary>Tips</summary>
你可以使用中文，如果你会的话
</details>

upstream: support UDP/TCP/DoT(TLS)/DoH(3)/DoQ
listener: support UDP/TCP/DoT(TLS)/DoH(s|3)/DoQ

You can use `plugin-matcher` to match white/black domain

example:
```
log:
  level: info

upstreams:
  - tag: Google
    type: tls
    address: 8.8.8.8

#  - tag: Google-UDP
#    type: udp
#    address: 8.8.8.8
#
#  - tag: Google-TCP
#    type: tcp
#    address: 8.8.8.8
#
#  - tag: Google-DoH
#    type: https
#    address: 8.8.8.8
#    # use-http3: true # Use HTTP/3
#
#  - tag: AdGuard-DoQ
#    type: quic
#    address: 94.140.14.14:784
#    servername: dns.adguard-dns.com # TLS SNI


plugin-matchers:
  - tag: blacklist
    type: domain
    args:
      # file: /path/to/blacklist
      rule:
        - suffix:ads.com
        - full:ad.com
        - keyword:ad
        - regex:^ad\.com$

workflows:
  - tag: default
    rules:
      - match-and:
          - plugin: # Use Plugin Matcher
              tag: blacklist # Plugin Matcher Tag
        exec: # Run Executors if match successfully
          - return: success # Return A Empty Response (SOA) (Rcode: Success)

      - exec:
          - upstream: Google # Send Request to upstream

listeners:
  - tag: TCP
    type: tcp
    listen: :53 # Listen [::]:53
    workflow: default # Workflow Tag

  - tag: UDP
    type: udp
    listen: :53 # Listen [::]:53
    workflow: default # Workflow Tag

#  - tag: TLS
#    type: tls
#    listen: :853
#    server-cert-file: /path/to/cert.pem
#    server-key-file: /path/to/key.pem
#
#  - tag: HTTPS
#    type: https
#    listen: :443
#    server-cert-file: /path/to/cert.pem
#    server-key-file: /path/to/key.pem
#
#  - tag: QUIC
#    type: quic
#    listen: :853
#    enable-0rtt: true # 0RTT Support (QUIC)
#    server-cert-file: /path/to/cert.pem
#    server-key-file: /path/to/key.pem
```
