### ISSUE TITLE
Upstream支持udpme

### ISSUE THREAD

**Issue by zhaibin18** [rnetx/cdns#2]
能否支持如下，多谢！
https://github.com/IrineSistiana/udpme

**Comment by 0xffffharry** [comment]
你可以试试：

```
upstreams:
  - tag: upstream
    type: udp
    address: 8.8.8.8
    edns0: true
```

实现参考了[https://github.com/IrineSistiana/udpme](https://github.com/IrineSistiana/udpme)，这是实验性的功能，不排除有什么奇怪的问题
