### ISSUE TITLE
请教一下你是怎么调试的..为什么一个测试文件都没有

### ISSUE THREAD

**Issue by duolabmeng6** [rnetx/cdns#4]

**Comment by 0xffffharry** [comment]
test 下有 listener 和 upstream 的测试，其余的在本地，由于没有脱敏，所以没有上传。后面有空会补上

**Comment by duolabmeng6** [comment]
谢谢 怪不得 玩不起来...原来如此 我开了http 但是访问没内容返回...调起来有点难受
```
- tag: listener
    type: http
    deal-timeout: 20s # 处理超时时间
    workflow: main

    listen: :88
 ```

**Comment by 0xffffharry** [comment]
http listener 其实就是doh，不开tls的话就是普通http，专门用来反向代理的。

```
listeners:
  - tag: http-listener
    type: http
    listen: :8999
    server-cert-file: cert.pem // tls 服务器证书
    server-key-file: key.pem // tls 服务器私钥
```

这就是一个标准的doh监听器
